#!/usr/bin/env python
"""
make_panels.py

Build clean four-panel MJO comparison figures (OBS / CNTRL / MEAN / CNN) for the
Weather and Climate Dynamics manuscript. This is a forked, generalized replacement
for the Panel_Figures/*.ipynb notebooks: those panelled FIVE columns (they included
an extra "partial CNN" experiment, f.e.FTORCHmjo_CNNmjo_DT2/DT3, labelled
"MITA1.0MJO1.0"). Here we drop that extra experiment by construction and keep exactly
four: ERA5 observations, CNTRL, the mean/climatological correction (MITA1.0), and the
state-dependent CNN correction (MITA1.0CNN0.3, experiment fullCNN_DT2).

Each diagnostic is the regression of a band-pass-filtered field onto the equatorial
Indian Ocean precipitation index, following the original notebooks: reg_coef_n(piom,
field) gives the slope map. Model files store the index as 'piom' and the field as
'<var>m'; observation files store 'pio' and '<var>'.

Inputs: the per-experiment NetCDF regenerated by Run_Diags_perexp_*.sh into
    Paper_WCD/nc/{CNTRL,MEAN,CNN}/<modout>.<suffix>
Observations are read from the CNN experiment's *_obs_all product (identical across
experiments, since all verify against the same ERA5/GPCP).

Run:  module load conda && conda activate npl-2024a && python make_panels.py [name ...]
Output: Paper_WCD/figures/fig_<name>.png
"""

import os
import sys
import numpy as np
import xarray as xr
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import ListedColormap
import cartopy.crs as ccrs
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
from scipy.stats import linregress
import warnings
warnings.filterwarnings("ignore")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                      # Paper_WCD/
NCDIR = os.path.join(ROOT, "nc")
FIGDIR = os.path.join(ROOT, "figures")
os.makedirs(FIGDIR, exist_ok=True)

# ----------------------------------------------------------------------------
# Experiment definitions. modout is the filename prefix each NCL run wrote.
# The extra experiment (CNNmjo_DT2/DT3) is deliberately absent.
# ----------------------------------------------------------------------------
EXPERIMENTS = [
    dict(key="obs",   label="a) ERA5",           dir="CNN",   modout="f.e.FTORCHmjo_fullCNN_DT2", obs=True),
    dict(key="cntrl", label="b) CNTRL",          dir="CNTRL", modout="f.e.FTORCHmjo_CNTRLmjo_DT2", obs=False),
    dict(key="mean",  label="c) MEAN",        dir="MEAN",  modout="f.e.FTORCHmjo_MEANmjo_DT2",  obs=False),
    dict(key="cnn",   label="d) CNN",  dir="CNN",   modout="f.e.FTORCHmjo_fullCNN_DT2", obs=False),
]

# ----------------------------------------------------------------------------
# Per-diagnostic configuration. suffix_model / suffix_obs are appended to the
# modout prefix. field_candidates lists acceptable field variable names (model
# first, then obs); the loader picks whichever is present.
# ----------------------------------------------------------------------------
DIAGNOSTICS = {
    "blmc925": dict(
        suffix_model="mjo_blmc925_model_all.nc",
        suffix_obs="mjo_blmc925_obs_all.nc",
        field_candidates=["u_timem", "u_time"],
        sign=-1.0,   # stored field is div(qV); negate so positive = convergence
        clevs=np.arange(-1.2, 1.3, 0.1),
        cmap="BrBG",
        cbar_label=r"$10^{-3}$ day$^{-1}$",
        title="Regressed 925 hPa moisture-flux convergence",
    ),
    "u850": dict(
        suffix_model="mjo_U850_model_all.850mb.80.100.nc",
        suffix_obs="mjo_U850_obs_all.850mb.nc",
        field_candidates=["u_timem", "u_time"],
        clevs=np.arange(-4.0, 4.5, 0.5),
        cmap="RdBu_r",
        cbar_label=r"[m s$^{-1}$]",
        title="Regressed 850 hPa zonal wind",
    ),
    "diah700": dict(
        suffix_model="mjo_diah2d_ll_model.nc",
        suffix_obs="mjo_diah2d_ll_obs.nc",
        field_candidates=["q1m_ll", "q1_ll"],
        level=700,               # q1m_ll is (time, level, lat, lon); select 700 hPa
        index_suffix="mjo_blmc925_model_all.nc",  # diah file has no embedded precip index; borrow it
        index_suffix_obs="mjo_blmc925_obs_all.nc",
        clevs=np.arange(-1.0, 1.05, 0.1),         # widened to avoid saturating the heating core
        cmap="RdBu_r",
        cbar_label=r"[K day$^{-1}$]",
        title="Regressed 700 hPa diabatic heating ($Q_1$)",
    ),
    "precip": dict(   # precipitation (mm/day): the convective envelope. In the blmc925
                      # product, v_timem/v_time store precipitation (model PRECT / obs PR),
                      # NOT meridional wind, so this panel is the regressed precip field.
        suffix_model="mjo_blmc925_model_all.nc",
        suffix_obs="mjo_blmc925_obs_all.nc",
        field_candidates=["v_timem", "v_time"],
        clevs=np.arange(-2.5, 2.6, 0.25),
        cmap="BrBG",
        cbar_label=r"[mm day$^{-1}$]",
        title="Regressed precipitation",
    ),
    "conindex": dict(
        suffix_model="mjo_conindex_model.nc",
        suffix_obs="mjo_conindex_obs.nc",
        field_candidates=["q_timem", "q_time"],
        clevs=None,              # autoscale
        cmap="RdBu_r",
        cbar_label=r"[K]",
        title="Regressed moist-instability index (theta_e 850--400 hPa)",
    ),
    # NOTE: 'ape' (mjo_ape_model_all.nc) is a longitude-height cross-section
    # q1m(time, level, lon), NOT a map. It needs a separate cross-section
    # builder and is handled elsewhere.
}

EXTENT = [40, 180, -20, 20]      # Indo-Pacific MJO domain (no dateline crossing)


def reg_coef_n(x, y):
    """Point-wise linear regression slope of y (t,lat,lon) on x (t,), from the
    original Panel_Figures notebooks."""
    x = np.asarray(x)
    ny, nx = y.shape[1], y.shape[2]
    slopes = np.zeros((ny, nx))
    for j in range(ny):
        for i in range(nx):
            slopes[j, i] = linregress(x, y[:, j, i]).slope
    return slopes


def load_slopes(path, field_candidates, level=None, index_path=None):
    """Open a per-experiment product and return (slopes, lons, lats, field).
    If index_path is given, the precip index (piom/pio) is read from there
    (used when the field file does not embed one, e.g. the diah2d product)."""
    ds = xr.open_dataset(path)
    ipath = index_path or path
    ids = xr.open_dataset(ipath) if index_path else ds
    idx_name = "piom" if "piom" in ids else ("pio" if "pio" in ids else None)
    if idx_name is None:
        raise KeyError(f"no precip index (piom/pio) in {ipath}: vars={list(ids.data_vars)}")
    pio = ids[idx_name].values.squeeze()
    # field variable
    field = None
    cands = field_candidates or []
    for name in cands:
        if name in ds:
            field = name
            break
    if field is None:
        # autodetect: first 3D float var that is not the index
        for name, da in ds.data_vars.items():
            if da.ndim == 3 and name not in (idx_name,):
                field = name
                break
    if field is None:
        raise KeyError(f"no 3D field var in {path}: vars={list(ds.data_vars)}")
    da = ds[field]
    if level is not None and "level" in da.dims:
        da = da.sel(level=level, method="nearest")
    if index_path is not None and "time" in da.dims and "time" in ids:
        # the field (e.g. raw Q1) spans the full daily series; align it to the
        # companion product's regression-window times so it matches the index.
        da = da.sel(time=ids["time"])
    arr = da.values
    if arr.ndim != 3:
        raise ValueError(f"{field} in {path} is {arr.ndim}D after level select; "
                         f"expected (time,lat,lon)")
    lons = ds["lon"].values
    lats = ds["lat"].values
    slopes = reg_coef_n(pio, arr)
    ds.close()
    return slopes, lons, lats, field


def build_panel(name, cfg):
    proj = ccrs.PlateCarree()
    fig = plt.figure(figsize=(13, 5.2))
    gs = gridspec.GridSpec(2, 2, figure=fig, wspace=0.10, hspace=0.28)
    axes = [fig.add_subplot(gs[i // 2, i % 2], projection=proj) for i in range(4)]

    clevs = cfg["clevs"]
    used_field = None
    mappable = None
    for ax, exp in zip(axes, EXPERIMENTS):
        suffix = cfg["suffix_obs"] if exp["obs"] else cfg["suffix_model"]
        path = os.path.join(NCDIR, exp["dir"], f"{exp['modout']}.{suffix}")
        if not os.path.exists(path):
            ax.text(0.5, 0.5, f"missing:\n{os.path.basename(path)}",
                    ha="center", va="center", transform=ax.transAxes, fontsize=11)
            ax.set_title(exp["label"], loc="left", fontsize=16)
            continue
        idx_path = None
        isuf = cfg.get("index_suffix_obs") if exp["obs"] else cfg.get("index_suffix")
        if isuf:
            idx_path = os.path.join(NCDIR, exp["dir"], f"{exp['modout']}.{isuf}")
        slopes, lons, lats, used_field = load_slopes(
            path, cfg["field_candidates"], level=cfg.get("level"), index_path=idx_path)
        slopes = slopes * cfg.get("sign", 1.0)   # e.g. negate div(qV) -> convergence-positive
        if clevs is None:  # autoscale on the first available field
            m = np.nanpercentile(np.abs(slopes), 98)
            clevs = np.linspace(-m, m, 21)
        ax.coastlines("50m", linewidth=0.5)
        mappable = ax.contourf(lons, lats, slopes, levels=clevs,
                               cmap=cfg["cmap"], extend="both", transform=proj)
        ax.set_xticks(np.arange(60, 181, 40), crs=proj)
        ax.set_yticks(np.arange(-20, 21, 10), crs=proj)
        ax.xaxis.set_major_formatter(LongitudeFormatter(number_format=".0f"))
        ax.yaxis.set_major_formatter(LatitudeFormatter(number_format=".0f"))
        ax.tick_params(labelsize=14)
        ax.set_extent(EXTENT, crs=proj)
        ax.text(0.985, 0.90, exp["label"], transform=ax.transAxes, ha="right",
                va="top", fontsize=16,
                bbox=dict(fc="white", ec="k", lw=0.8))

    if mappable is not None:
        cbar_ax = fig.add_axes([0.25, 0.06, 0.5, 0.02])
        cbar = fig.colorbar(mappable, cax=cbar_ax, orientation="horizontal")
        cbar.set_label(cfg["cbar_label"], fontsize=15)
        cbar.ax.tick_params(labelsize=13)
    # no figure title: the manuscript caption serves this role
    out = os.path.join(FIGDIR, f"fig_{name}.png")
    fig.savefig(out, bbox_inches="tight", dpi=300)
    plt.close(fig)
    print(f"[make_panels] wrote {out}  (field var: {used_field})")
    return out


def main(argv):
    names = argv[1:] if len(argv) > 1 else list(DIAGNOSTICS.keys())
    for name in names:
        if name not in DIAGNOSTICS:
            print(f"[make_panels] unknown diagnostic '{name}'; "
                  f"choices: {list(DIAGNOSTICS)}")
            continue
        try:
            build_panel(name, DIAGNOSTICS[name])
        except Exception as e:  # keep going across diagnostics
            print(f"[make_panels] {name} FAILED: {e}")


if __name__ == "__main__":
    main(sys.argv)
